# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Location.create(name: "Fountainfaux - SoBe", city: "Miami Beach", state:"FL", description: "A boutique hotel of South Beach")
# Location.create(name: "Faux Seasons - Keys", city: "Islamorada", state: "FL", description: "A luxury resort in the Keys")
# Location.create(name: "The Faux - Brickell", city: "Miami", state: "FL", description: "A prime Brickell location as trendy as it's name.")

# Room.create(room_number: 11, room_type: "ocean-front", location_id: 1, status: "ready")
# Room.create(room_number: 12, room_type: "ocean-front", location_id: 1, status: "ready")
# Room.create(room_number: 13, room_type: "garden-view", location_id: 1, status: "ready")
# Room.create(room_number: 14, room_type: "garden-view", location_id: 1, status: "ready")
# Room.create(room_number: 21, room_type: "ocean-front", location_id: 1, status: "ready")
# Room.create(room_number: 22, room_type: "ocean-front", location_id: 1, status: "ready")
# Room.create(room_number: 23, room_type: "garden-view", location_id: 1, status: "ready")
# Room.create(room_number: 24, room_type: "garden-view", location_id: 1, status: "ready")
# Room.create(room_number: 31, room_type: "ocean-front", location_id: 1, status: "ready")
# Room.create(room_number: 32, room_type: "ocean-front", location_id: 1, status: "ready")
# Room.create(room_number: 33, room_type: "garden-view", location_id: 1, status: "ready")
# Room.create(room_number: 34, room_type: "garden-view", location_id: 1, status: "ready")
# Room.create(room_number: 41, room_type: "ocean-front", location_id: 1, status: "ready")
# Room.create(room_number: 42, room_type: "ocean-front", location_id: 1, status: "ready")
# Room.create(room_number: 43, room_type: "garden-view", location_id: 1, status: "ready")
# Room.create(room_number: 44, room_type: "garden-view", location_id: 1, status: "ready")

# Room.create(room_number: 101, room_type: "ocean-front-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 102, room_type: "ocean-front-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 103, room_type: "ocean-front-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 104, room_type: "ocean-front-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 105, room_type: "ocean-front-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 106, room_type: "ocean-view-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 107, room_type: "ocean-view-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 108, room_type: "ocean-view-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 109, room_type: "ocean-view-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 110, room_type: "ocean-view-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 111, room_type: "ocean-view-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 112, room_type: "garden-view-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 113, room_type: "garden-view-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 114, room_type: "garden-view-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 115, room_type: "garden-view-swim-out", location_id: 2, status: "ready")
# Room.create(room_number: 201, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 202, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 203, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 204, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 205, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 206, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 207, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 208, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 209, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 210, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 211, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 212, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 213, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 214, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 215, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 301, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 302, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 303, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 304, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 305, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 306, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 307, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 308, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 309, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 310, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 311, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 312, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 313, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 314, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 315, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 401, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 402, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 403, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 404, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 405, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 406, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 407, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 408, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 409, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 410, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 411, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 412, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 413, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 414, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 415, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 501, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 502, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 503, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 504, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 505, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 506, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 507, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 508, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 509, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 510, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 511, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 512, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 513, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 514, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 515, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 601, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 602, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 603, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 604, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 605, room_type: "ocean-front", location_id: 2, status: "ready")
# Room.create(room_number: 606, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 607, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 608, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 609, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 610, room_type: "ocean-view", location_id: 2, status: "ready")
# Room.create(room_number: 611, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 612, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 613, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 614, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 615, room_type: "garden-view", location_id: 2, status: "ready")
# Room.create(room_number: 701, room_type: "ocean-front-ph", location_id: 2, status: "ready")
# Room.create(room_number: 702, room_type: "ocean-front-ph", location_id: 2, status: "ready")
# Room.create(room_number: 703, room_type: "ocean-front-ph", location_id: 2, status: "ready")
# Room.create(room_number: 704, room_type: "ocean-front-ph", location_id: 2, status: "ready")
# Room.create(room_number: 705, room_type: "ocean-front-ph", location_id: 2, status: "ready")
# Room.create(room_number: 706, room_type: "ocean-view-ph", location_id: 2, status: "ready")
# Room.create(room_number: 707, room_type: "ocean-view-ph", location_id: 2, status: "ready")
# Room.create(room_number: 708, room_type: "garden-view-ph", location_id: 2, status: "ready")
# Room.create(room_number: 709, room_type: "garden-view-ph", location_id: 2, status: "ready")
# Room.create(room_number: 710, room_type: "garden-view-ph", location_id: 2, status: "ready")


# Room.create(room_number: 101, room_type: "bay-view-swim-out", location_id: 3, status: "ready")
# Room.create(room_number: 102, room_type: "bay-view-swim-out", location_id: 3, status: "ready")
# Room.create(room_number: 103, room_type: "bay-view-swim-out", location_id: 3, status: "ready")
# Room.create(room_number: 104, room_type: "bay-view-swim-out", location_id: 3, status: "ready")
# Room.create(room_number: 105, room_type: "bay-view-swim-out", location_id: 3, status: "ready")
# Room.create(room_number: 106, room_type: "city-view-swim-out", location_id: 3, status: "ready")
# Room.create(room_number: 107, room_type: "city-view-swim-out", location_id: 3, status: "ready")
# Room.create(room_number: 108, room_type: "city-view-swim-out", location_id: 3, status: "ready")
# Room.create(room_number: 109, room_type: "city-view-swim-out", location_id: 3, status: "ready")
# Room.create(room_number: 201, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 202, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 203, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 204, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 205, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 206, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 207, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 208, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 209, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 210, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 301, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 302, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 303, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 304, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 305, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 306, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 307, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 308, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 309, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 310, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 401, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 402, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 403, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 404, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 405, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 406, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 407, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 408, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 409, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 410, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 401, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 402, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 403, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 404, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 405, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 406, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 407, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 408, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 409, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 410, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 501, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 502, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 503, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 504, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 505, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 506, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 507, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 508, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 509, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 510, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 601, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 602, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 603, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 604, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 605, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 606, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 607, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 608, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 609, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 610, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 701, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 702, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 703, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 704, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 705, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 706, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 707, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 708, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 709, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 710, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 801, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 802, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 803, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 804, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 805, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 806, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 807, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 808, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 809, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 810, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 901, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 902, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 903, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 904, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 905, room_type: "bay-view", location_id: 3, status: "ready")
# Room.create(room_number: 906, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 907, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 908, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 909, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 910, room_type: "city-view", location_id: 3, status: "ready")
# Room.create(room_number: 1001, room_type: "bay-view-ph", location_id: 3, status: "ready")
# Room.create(room_number: 1002, room_type: "bay-view-ph", location_id: 3, status: "ready")
# Room.create(room_number: 1003, room_type: "bay-view-ph", location_id: 3, status: "ready")
# Room.create(room_number: 1004, room_type: "city-view-ph", location_id: 3, status: "ready")
# Room.create(room_number: 1005, room_type: "city-view-ph", location_id: 3, status: "ready")
# Room.create(room_number: 1006, room_type: "city-view-ph", location_id: 3, status: "ready")

#User.create(email: "graycie@sobe.com", password: "password", first_name: "Graycie", last_name: "The Cat")

long_start = DateTime.new(2020,5,28)
long_end = DateTime.new(2020,5,31)
long_range = (long_start..long_end).to_a


short_start = DateTime.new(2020,5,29)
short_end = DateTime.new(2020,5,30)
short_range = (short_start..short_end).to_a


#2 seeds showing 2 long weekend reservations at location 1
# Reservation.create(start_date: long_start, end_date: long_end, date_range: long_range, user_id: 1, room_id: 13, location_id: 1)
# Reservation.create(start_date: long_start, end_date: long_end, date_range: long_range, user_id: 1, room_id: 14, location_id: 1)


# #rest of seeds for location 1, efford to disable or not show dates avail for fri and sat of same weekend, so fri and sat are compl booked at loc 1
# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 1, location_id: 1)
# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 2, location_id: 1)
# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 3, location_id: 1)
# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 4, location_id: 1)

# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 5, location_id: 1)
# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 6, location_id: 1)
# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 7, location_id: 1)
# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 8, location_id: 1)

# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 9, location_id: 1)
# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 10, location_id: 1)
# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 11, location_id: 1)
# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 12, location_id: 1)

# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 15, location_id: 1)
# Reservation.create(start_date: short_start, end_date: short_end, date_range: short_range, user_id: 1, room_id: 16, location_id: 1)

